version: "3"
services:
  engecopi:
    image: tomcat:8
    container_name: eng_pedido_entrega2
    ports:
      - "8083:8080"
    environment:
      TZ: "America/Fortaleza"
      EBEAN_PROPS: /etc/ebean.properties
    volumes:
      - ./build/libs/pedidosEntrega-1.0.war:/usr/local/tomcat/webapps/pedidosEntrega.war
      - ./ebean.properties:/etc/ebean.properties
    restart: always
    networks:
      rede_pedido_entrega2:
        ipv4_address: 172.51.1.1
networks:
  rede_pedido_entrega2:
    ipam:
      driver: default
      config:
        - subnet: 172.51.0.0/16
